<a href="https://www.kaggle.com/code/riteshkumarweb/bagging-classifier-ensemble-learning?scriptVersionId=319285708" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/shravan3273/breast-cancer-classifiction/breastcancer.csv

In [24]:
# 📊 Bagging (Bootstrap Aggregating)

# Bagging is an Ensemble Learning technique

# 🎯 Goal:
# Improve accuracy and reduce overfitting

# 🧠 Idea:
# Train multiple models on different random subsets
# of the dataset and combine their predictions

# 📦 Bootstrap:
# Random sampling WITH replacement

# Means:
# Same data point can appear multiple times
# in one sampled dataset

# 📊 Aggregating:
# Combine predictions from all models

# For Classification:
# → Majority Voting 🗳️

# For Regression:
# → Average Prediction 📈


# 🔁 Working of Bagging:

# Step 1️⃣
# Create multiple random datasets from original data

# Step 2️⃣
# Train separate models on each dataset

# Step 3️⃣
# Collect predictions from all models

# Step 4️⃣
# Combine predictions for final output


# 📦 Commonly used with:
# 🌳 Decision Trees

# Example:
# Random Forest = Bagging + Decision Trees


# 🎯 Advantages:
# ✅ Reduces overfitting
# ✅ Improves stability
# ✅ Better accuracy
# ✅ Works well on high variance models

# ❌ Disadvantages:
# ❌ Slower
# ❌ More memory usage
# ❌ Less interpretable


# 📊 Simple Diagram:

#                📥 Original Dataset
#                         │
#       ┌─────────────────┼─────────────────┐
#       │                 │                 │
#   📦 Sample1        📦 Sample2        📦 Sample3
#       │                 │                 │
#    🌳 Tree1          🌳 Tree2          🌳 Tree3
#       │                 │                 │
#       └─────────────────┼─────────────────┘
#                         │
#               🗳️ Voting / Averaging
#                         │
#                  ✅ Final Prediction

In [2]:
df = pd.read_csv('/kaggle/input/datasets/shravan3273/breast-cancer-classifiction/breastcancer.csv')

In [3]:
df.isnull().sum()

id                         0
diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

In [4]:
df

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [5]:
df.drop(columns=['id'],inplace=True)

In [6]:
df['diagnosis'].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [7]:
X = df.iloc[:,1:]
X

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [8]:
y = df.iloc[:,0]
y

0      M
1      M
2      M
3      M
4      M
      ..
564    M
565    M
566    M
567    M
568    B
Name: diagnosis, Length: 569, dtype: object

In [9]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['diagnosis'] = encoder.fit_transform(y)

In [10]:
from sklearn.datasets import make_classification
from sklearn.metrics import accuracy_score
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train,y_train)
y_pred = dt.predict(X_test)

print("Decision Tree accuracy", accuracy_score(y_test,y_pred))

Decision Tree accuracy 0.9473684210526315

In [11]:
X_train.shape

(455, 30)

In [12]:
y_train.shape

(455,)

# **Type of Bagging**

In [13]:
# =========================================================
#              TYPES OF ENSEMBLE LEARNING
# =========================================================


# 1️⃣ BAGGING
# ---------------------------------------------------------
#
#          Random Samples from Dataset
#
#        ┌────────┬────────┬────────┐
#        ▼        ▼        ▼
#      Tree1    Tree2    Tree3
#
#        └────────┼────────┘
#                 ▼
#          Voting / Average
#                 ▼
#          Final Prediction
#
# Goal:
# - Reduce Variance
# - Reduce Overfitting
#
# Example:
# - Random Forest
#
# =========================================================


# 2️⃣ BOOSTING
# ---------------------------------------------------------
#
#          Model 1
#             ▼
#      Correct Mistakes
#             ▼
#          Model 2
#             ▼
#      Correct Mistakes
#             ▼
#          Model 3
#             ▼
#      Final Prediction
#
# Goal:
# - Reduce Bias
#
# Examples:
# - AdaBoost
# - XGBoost
#
# =========================================================


# 3️⃣ VOTING
# ---------------------------------------------------------
#
#        KNN  ────┐
#        Tree ────┼──► Voting ─► Final Prediction
#        SVM  ────┘
#
# Goal:
# - Combine Different Algorithms
#
# =========================================================


# 4️⃣ STACKING
# ---------------------------------------------------------
#
#        KNN  ────┐
#        Tree ────┼──► Meta Model ─► Final Prediction
#        SVM  ────┘
#
# Goal:
# - Learn Best Combination of Models
#
# =========================================================

# Simple Bagging with DicisionTree

In [14]:
bag_a = BaggingClassifier(
estimator=DecisionTreeClassifier(), #Creating Decision Tree as base estimator
n_estimators=500, #Creating 500 Decision Tree models
max_samples=0.25, #Taking 25% random samples for each model
bootstrap=True, #Enabling sampling with replacement
random_state=42 #Fixing random behavior for same results
)
bag_a.fit(X_train ,y_train)
y_pred = bag_a.predict(X_test)
accuracy_score(y_test,y_pred)

0.956140350877193

⚠️ IMPORTANT:
 - Dataset is NOT divided equally ❌
 - Each tree randomly samples data ✅ or select data from the dataset 
 - Same row can appear many times ✅ if bootsrap is true 
 - bootstrap=True → repetition allowed

In [15]:
#                  BAGGING WORKFLOW
#
#               Original Dataset
#             X_train = 455 Rows
#
#          ┌──────────────────────┐
#          │      455 Rows        │
#          └──────────────────────┘
#                     │
#     ┌───────────────┼───────────────┐
#     │               │               │
#     ▼               ▼               ▼
#
# Random Sample   Random Sample   Random Sample
#   (~114 rows)     (~114 rows)     (~114 rows)
#
#     │               │               │
#     ▼               ▼               ▼
#
#   Tree 1          Tree 2          Tree 3
#
#     │               │               │
#     └───────────────┼───────────────┘
#                     ▼
#
#              Majority Voting
#                     ▼
#
#              Final Prediction
#
#
# IMPORTANT:
# - Dataset is NOT divided equally ❌
# - Each tree randomly samples data ✅
# - Same row can appear many times ✅
# - bootstrap=True → repetition allowed

# Bagging using SVM

In [16]:
from sklearn.svm import SVC

bag_b = BaggingClassifier(
estimator=SVC(),
n_estimators=500,
max_samples=0.25,
bootstrap=True,
random_state=42)

bag_b.fit(X_train,y_train)
y_pred = bag_b.predict(X_test)
print("Bagging using SVM", accuracy_score(y_test,y_pred))

Bagging using SVM 0.9385964912280702

⚠️ IMPORTANT:
 - Dataset is NOT divided equally ❌
 - Each tree randomly samples data ✅ or select data from the dataset 
 - Same row can appear many times ✅ if bootsrap is true 
 - bootstrap=True → repetition allowed

# Pasting 
Same as simple bagging or bagging but no reapeated sample so 
bootstrap = False , sample means random data from the point not sequence
wise,like we do  **df.sample(10)** like this

In [17]:
bag_c = BaggingClassifier(
estimator=DecisionTreeClassifier(), #Creating Decision Tree as base estimator
n_estimators=500, #Creating 500 Decision Tree models
max_samples=0.25, #Taking 25% random samples for each model
bootstrap=False, #Disabling sampling with replacement
random_state=42, #Fixing random behavior for same results
#verbose=1, #Showing training progress information
n_jobs=1 #Using all CPU cores for faster processing
)
,
bag_c.fit(X_train,y_train)
y_pred = bag_c.predict(X_test)
print("Pasting classifier", accuracy_score(y_test,y_pred))

Pasting classifier 0.956140350877193

⚠️ IMPORTANT:
 - Dataset is NOT divided equally ❌
 - Each tree randomly samples data ✅ or select data from the dataset 
 - Same row can appear many times ✅ if bootsrap is true 
 - bootstrap=True → repetition allowed

# Random Subspaces
Instead of Row Sampling rows , we do feature/columns sampling(shuffle) . if data has Age salary, Height ,Wight, then , one model may train on Age+ Height and another on salary+ Weight.

In [18]:
bag_d = BaggingClassifier(
estimator=DecisionTreeClassifier(), #Creating Decision Tree as base estimator
n_estimators=500, #Creating 500 Decision Tree models
max_samples=1.0, #Using 100% rows from training data for each model
bootstrap=False, #Disabling sampling with replacement for rows
max_features=0.5, #Taking 50% random features/columns for each model
    #if the datset has 30 features or column then it randomdly select
    #15 column is it set to 0.5 
bootstrap_features=True, #Enabling sampling with replacement for features
random_state=42 #Fixing random behavior for same results
)

bag_d.fit(X_train,y_train)
y_pred = bag_d.predict(X_test)
print("Random Subspaces classifier", accuracy_score(y_test,y_pred))

Random Subspaces classifier 0.9649122807017544

⚠️ IMPORTANT:
 - Dataset is NOT divided equally ❌
 - Each tree randomly samples data ✅ or select data from the dataset 
 - Same row can appear many times ✅ if bootsrap is true 
 - bootstrap=True → repetition allowed

In [19]:
bag_d.estimators_features_ # index number of columns who is randomdly selected

[array([27,  9, 26, 10, 12,  2,  9,  7, 28,  7, 24, 19, 18, 24, 29]),
 array([14, 23, 19, 23, 19, 25,  5, 10,  3,  9, 15, 10, 16, 19,  8]),
 array([22, 14,  0,  7,  7, 25, 26,  8, 28, 21, 24, 18, 21, 14, 20]),
 array([ 0,  5, 23, 10, 12,  4, 17, 19, 22, 18, 21, 11,  3, 17,  2]),
 array([13,  6, 25,  6, 11,  3, 15,  3,  8,  3, 23,  8, 22, 26, 16]),
 array([21, 18,  1, 18,  7, 25, 19, 13, 13, 17, 13,  3, 15,  6, 17]),
 array([12, 12, 19, 29,  2, 10, 17, 21,  2,  3, 17,  5,  5, 26, 15]),
 array([14, 11,  6, 18, 24, 14,  2,  5, 25, 16, 20, 15, 26, 15,  3]),
 array([ 8, 28, 12, 10, 29,  4, 13, 20,  3, 13, 18, 12, 19, 22, 12]),
 array([ 8, 13, 17, 24, 14,  9, 28, 16,  7, 22, 26, 14, 26, 12,  8]),
 array([19, 18,  9, 24,  4, 11,  6, 22, 28, 28, 19, 28,  4,  2, 23]),
 array([ 4, 23, 24, 22, 10, 23, 14, 17, 12,  9, 23,  2,  8, 21, 28]),
 array([19,  9, 26, 10, 29,  4,  8, 13, 10, 27,  6,  1,  5, 13, 15]),
 array([ 0, 25, 29, 22,  7, 14,  4,  0,  5,  9, 28, 13, 29, 25,  5]),
 array([16, 13,  8,  2,  0, 18, 27, 13, 12, 13, 22,  0, 19, 14, 11]),
 array([24, 20, 22,  6,  8, 17, 22, 19,  0,  5,  1, 13, 14, 18,  2]),
 array([15, 11, 23, 23,  2, 16, 26, 13, 29, 19,  7, 10, 21, 24, 21]),
 array([24,  4,  2, 15,  8, 17, 20,  6, 11, 14, 22,  2, 13, 20, 20]),
 array([ 7, 20, 18, 28,  8, 10, 15,  6, 24, 22,  4,  5, 21, 18, 10]),
 array([ 8, 29, 12,  1, 13, 21, 16, 27,  2, 23,  6, 26, 16, 12,  9]),
 array([21, 24,  8, 19, 16, 12, 21, 14,  3,  2, 17, 12, 28, 11, 21]),
 array([12, 28, 20,  6,  2, 23, 29, 23, 24, 28,  5,  7,  0,  3, 14]),
 array([15, 17, 13, 13, 11,  5,  2, 23, 17,  7,  8, 16, 24, 11, 22]),
 array([24, 28, 24, 29, 22, 25, 25, 18, 25,  9, 11, 20, 14, 16,  6]),
 array([11,  1,  4, 28, 18, 19, 15, 13,  7,  3,  1, 10,  9,  2, 24]),
 array([20,  1, 11, 29, 19,  1, 20,  1,  1, 10, 10,  5, 29, 28, 20]),
 array([24, 24, 16, 26, 16,  8, 28,  8, 29,  1, 11, 11, 15,  8, 21]),
 array([ 4, 15, 13,  2, 29, 26, 19, 18, 24, 13, 13,  5,  6,  7, 29]),
 array([27,  2, 27, 23, 28, 24,  8, 13, 22,  7, 20,  9, 27, 17, 23]),
 array([29, 11, 24, 27,  5,  2, 15, 26,  7, 20, 27,  9, 19,  6, 15]),
 array([26, 19, 12, 16, 28, 13, 22, 29,  0, 26, 11, 22, 22, 29, 11]),
 array([23, 22, 13, 27,  8, 27, 26, 28,  0, 20, 16,  9, 24, 20, 22]),
 array([19, 15, 25, 23, 29,  5, 24, 15,  7, 12, 23, 15,  2, 29, 14]),
 array([ 4,  5, 16,  5, 20, 10, 25,  9, 22, 24, 13, 12,  5, 24,  1]),
 array([29, 20, 24,  7, 18,  0,  1, 17, 14, 19, 24,  5, 20, 29,  2]),
 array([25, 18, 27, 14, 28, 17,  0, 16,  8,  2, 16,  2,  0, 16, 12]),
 array([24, 20, 14, 20,  1, 21,  4, 27, 22, 20,  3, 26,  4, 10, 26]),
 array([ 9,  7, 25,  3, 12, 24, 22,  7, 28,  2, 10, 18, 18,  9, 26]),
 array([ 8,  8, 25, 22, 29, 29, 11, 14,  3,  4, 14,  0, 21, 20, 19]),
 array([15, 11,  8, 10,  9,  5, 19,  5, 18,  0,  4, 12, 26, 22, 25]),
 array([27, 15,  9,  8, 17, 21,  5,  8, 12, 15,  6,  4, 15, 18, 18]),
 array([ 7,  7, 17,  0, 12, 27, 25, 25, 21,  4, 29, 13, 13,  6, 24]),
 array([ 6,  1, 28, 25, 25,  7,  5,  3,  2, 16, 17,  9, 21,  1, 13]),
 array([18,  3, 25, 23, 19,  3, 20, 14, 11,  4,  8, 21,  3, 16, 23]),
 array([16,  6, 24,  7, 25, 10, 21, 23,  3, 18,  5, 10, 12, 15, 20]),
 array([28, 12, 20, 14, 10, 13, 14, 15, 22, 28, 19,  6, 12, 27, 16]),
 array([14, 12,  1, 20,  1, 17,  8, 16, 20, 16, 18, 13, 15,  2, 16]),
 array([12, 29, 23, 13, 17, 17, 23,  9, 18, 11, 15,  4, 13, 29, 13]),
 array([ 1, 16, 21,  1, 25,  6,  8,  7, 29,  8,  2, 11, 27, 28, 10]),
 array([26, 23, 19, 18,  0, 29, 11, 11,  0, 24, 13, 25,  5,  8,  8]),
 array([ 6, 15, 12, 15,  1, 27, 29, 26, 21,  6, 28, 15, 28, 27, 22]),
 array([ 6, 12,  9, 28,  7,  9, 22,  1,  6,  5, 27, 13,  3, 27,  3]),
 array([17,  7,  0,  1,  0,  7, 29, 13,  9,  7,  4,  5, 21,  8,  5]),
 array([27, 27,  4, 21, 24,  5, 21, 26,  7, 23,  8,  2, 29,  8, 26]),
 array([19, 16, 18, 18, 20, 29, 21, 18,  4, 22,  5,  3, 11, 14,  1]),
 array([13,  6, 27, 12,  6,  7, 26, 13, 13, 20,  5,  0, 23, 21, 26]),
 array([12, 21, 23, 29, 23,  8,  0, 24, 15, 22, 27, 28,  0, 17, 21]),
 array([24, 17,  8, 19, 17, 21, 19, 21,  3, 22, 28,  9, 12, 26, 29]),
 array([22, 22, 22, 19, 19, 23, 19, 12, 20,  2,  2, 28, 10, 27,  4]),
 array([ 1, 16, 22, 22, 22, 19, 18, 18, 14, 17, 23, 15,  1, 19,  3]),
 array([ 8, 12,  6,  6,  8,  9,  8, 25, 26,  7,  2,  8,  2, 24, 15]),
 array([ 6, 26, 29, 21, 15,  0,  2,  2, 10,  4, 22, 22, 28, 24, 27]),
 array([19, 24, 16, 18, 11, 23,  4, 15,  6, 12, 18,  0,  0, 13, 26]),
 array([ 3, 26,  7, 26, 14, 18,  6,  4, 11, 23, 28, 10, 23, 26,  2]),
 array([ 4,  2, 23, 19, 24,  9, 27, 29, 24,  7, 14, 29,  4, 15, 26]),
 array([15, 22,  1, 10, 17,  6,  7,  8, 24, 28,  4, 25, 22, 29,  2]),
 array([ 1, 23, 11, 26,  9,  3, 23, 15, 23,  3, 22, 17,  5,  5,  4]),
 array([24,  6,  7, 29, 25, 12,  5, 22,  2, 24,  2, 11, 10,  7,  9]),
 array([ 0, 11, 28,  0, 27,  7,  9,  2,  4, 12, 20,  7, 19,  8, 15]),
 array([15, 27,  5, 28, 12, 28, 17, 12,  5, 22, 23, 21, 21, 12,  9]),
 array([ 6, 15, 21, 23, 26, 26,  1, 18, 13, 24, 27, 29,  7,  4, 26]),
 array([10, 24, 19,  0, 21, 24,  6,  6, 27,  8, 18,  9, 17, 25, 19]),
 array([ 5, 29, 15, 25,  9, 13,  7, 19, 25,  3, 29, 18,  1, 12,  2]),
 array([16, 26,  1,  3, 27, 24,  2,  2, 14, 24,  7, 29,  3, 10,  3]),
 array([16,  7, 27, 11,  1, 19,  4,  6, 21, 22, 18, 10, 10, 24, 17]),
 array([10, 10, 17, 24, 12, 13, 25,  7, 19, 15, 15,  1, 16, 27, 22]),
 array([24, 20,  6, 20,  8, 25, 27,  6, 13, 24,  1,  4,  4,  1,  8]),
 array([13,  2, 27, 25,  8, 28, 14, 26,  6, 26, 29, 20, 16,  3,  9]),
 array([ 7, 19, 24, 20, 10, 16, 29, 22, 25,  2,  7, 18, 10, 16,  5]),
 array([12, 29, 14, 24, 29, 21, 24, 23,  6, 18, 18, 10, 21, 12,  8]),
 array([14,  7, 16, 16, 27,  4,  6, 29,  0, 22, 11,  2, 14, 22, 28]),
 array([24, 27,  2,  8, 20, 12, 13, 23, 28,  7,  5,  2, 20, 12, 10]),
 array([22, 21, 13,  5, 28, 25, 18, 20,  6,  4, 19, 27,  8, 22,  9]),
 array([29, 17,  1, 18,  4,  5,  8,  3,  1, 16, 23, 27, 24,  6, 17]),
 array([ 4, 18,  1,  8, 25,  7, 28, 18, 14, 17, 11, 23,  1, 23,  9]),
 array([14, 12,  3, 21, 18, 25, 23,  6, 28,  2, 27,  2, 22, 22,  9]),
 array([21,  4, 17, 25, 28,  2,  6,  9,  3, 13, 22, 10, 21, 20,  6]),
 array([23, 28,  8, 27, 16,  0, 26, 22, 26, 18, 14, 26, 17,  7,  0]),
 array([21,  9, 29, 25, 25, 21, 11, 26, 13, 10, 11, 17, 23,  4, 17]),
 array([11, 28, 14, 26, 15, 10,  4, 15, 22, 19, 18, 26, 28, 18, 25]),
 array([13,  3, 22, 16, 20, 28,  7,  6, 23, 19, 27, 10, 19,  4, 10]),
 array([10,  0, 13,  0, 26, 17, 27,  4, 16,  4, 26, 11, 22, 26, 18]),
 array([25, 22,  5,  4, 11, 25, 29,  2, 14,  1, 12, 20,  0, 15,  2]),
 array([21,  0, 12,  9, 24,  5,  5,  3, 12,  7,  8,  0, 22, 17, 25]),
 array([ 6, 17,  6, 24, 10,  6, 24, 23, 17, 26, 29,  4, 21,  1, 25]),
 array([11,  9, 13,  9, 19,  8, 24, 23,  0, 11, 22, 25, 17, 10,  6]),
 array([ 8, 27, 18,  1, 25,  8,  7, 20, 28, 15, 19,  8, 12, 12,  8]),
 array([18, 26,  1, 20,  4, 13, 13, 28, 14, 26, 21, 12, 10,  1, 25]),
 array([ 3, 27, 12, 18, 27,  9,  0,  8, 17,  2, 23,  9, 16,  9, 28]),
 array([14, 22, 15, 10,  0,  5, 11, 14, 17, 14,  3, 21,  4, 25,  8]),
 array([ 6, 19,  8,  5, 14, 21,  5, 29,  0, 15, 24,  3, 17, 18,  5]),
 array([25, 14, 20, 16, 15, 15,  0, 23, 29, 13, 23,  2, 26, 13, 12]),
 array([24, 14, 10, 15,  9, 26, 18, 20,  7, 10,  8,  6, 11, 14, 14]),
 array([11, 29, 18, 15, 12, 10, 19,  3,  6,  8, 14, 15,  0, 11, 13]),
 array([21,  6,  3,  4, 22, 27, 10, 22, 18,  2, 29,  4, 12,  0, 24]),
 array([ 0, 24, 29,  6, 19, 19, 13, 17, 29, 24,  6,  6, 17, 19,  8]),
 array([25,  3,  2, 12, 26,  9,  6,  6, 12,  6, 16, 13, 21, 23, 20]),
 array([13, 27,  3, 11, 12, 25,  6, 29,  0, 10, 23, 22,  9, 16,  2]),
 array([18, 25,  9, 28, 14, 28,  8,  6, 27, 22, 22, 14, 11,  2,  0]),
 array([ 4, 28, 27, 29, 22, 20, 27, 21, 10, 28,  7,  9,  6, 28, 13]),
 array([26,  8, 21,  2, 16, 13, 16, 15,  1, 16,  6, 21, 28, 14, 10]),
 array([14,  7, 21, 27, 29,  2, 20, 25, 17, 26, 12, 26, 12, 29, 11]),
 array([11,  8, 22,  0,  7,  8, 15, 27, 18,  7, 20, 27,  7, 15, 26]),
 array([22,  5, 28,  1, 23, 22, 14, 29, 20, 15, 20, 16, 18, 26,  0]),
 array([26, 12,  9,  3, 21,  0,  2, 22, 12, 14, 10,  6,  4, 27, 13]),
 array([27, 22,  0, 22, 15,  1, 16, 19, 14, 11, 11, 27,  9, 25, 16]),
 array([22,  4,  8, 16, 12, 25, 17, 13, 12, 26,  2, 27,  7, 26,  6]),
 array([ 9, 12, 28, 10, 21, 21, 11, 27, 21,  3, 27, 20,  4,  5, 20]),
 array([ 2, 22, 14, 13,  7, 24,  6, 28, 21,  2, 13, 25,  5, 25, 29]),
 array([ 9, 25, 20, 21, 11, 23, 28,  6, 20,  5,  5, 17, 11,  0, 28]),
 array([13,  2,  7,  4, 26, 26, 21,  5, 26, 10, 19, 22, 27, 15, 21]),
 array([ 2, 29, 28, 19, 14,  1, 29,  3,  0, 18, 14,  9, 13, 26,  4]),
 array([ 2, 12, 27, 17, 16, 13, 12,  2, 27, 11, 17, 18,  6, 18, 22]),
 array([ 8,  2, 17, 22, 26, 16,  9, 19, 21,  1,  6, 11, 19,  8, 19]),
 array([15, 27, 18, 11,  3, 28, 23, 13,  8,  4, 18,  7, 16, 11,  0]),
 array([16, 10, 10, 12,  1, 21, 27, 23,  2, 17, 12, 18,  8, 13, 12]),
 array([ 0, 17,  3,  2, 24, 12, 18, 26, 22,  8, 20, 20,  7, 13, 11]),
 array([14, 21, 13, 28, 25, 15, 18, 16, 16,  0,  7,  6, 13, 15, 13]),
 array([10,  5,  6, 18,  5, 12, 26, 10, 11, 14, 12,  7,  2,  0, 11]),
 array([ 8,  1, 24, 23,  5, 14, 29,  2, 16, 27, 23,  6, 14, 26,  0]),
 array([18,  0, 14,  0, 28, 11,  7, 19, 16,  8, 15, 20,  7, 15, 10]),
 array([17, 28, 13, 21,  9,  8, 11, 10, 23,  3, 25, 28, 28,  8, 26]),
 array([29, 25, 22, 20, 27,  8,  1, 12,  6, 27, 16,  1,  6, 16,  2]),
 array([13,  8, 14,  0,  6, 12, 19, 14, 22,  7, 11,  0,  3,  8, 10]),
 array([ 6,  9, 17, 20, 21,  0, 11,  7, 12, 27, 29, 25, 13,  0,  9]),
 array([25, 16,  0,  3, 29, 11, 14, 10, 25, 17, 18,  6,  2, 29, 26]),
 array([24,  3, 25,  7,  7, 26, 23,  1, 21, 28, 11,  9, 13, 20, 28]),
 array([29, 12,  8, 23, 19, 22,  1, 12,  7, 22,  1,  5,  2,  5, 29]),
 array([ 1,  8,  5, 13, 18,  7, 25,  6, 25,  1,  9, 14, 11, 16, 16]),
 array([20,  8,  6, 14, 29, 11, 13,  1, 21, 21, 13, 15, 25, 17,  4]),
 array([23,  5, 28, 13, 10,  4,  6, 16, 24,  7, 28, 17, 14, 16,  5]),
 array([26,  7,  7,  6, 15, 18,  1,  3,  4,  7, 16, 27,  3,  3, 23]),
 array([ 5,  5, 26, 24, 25,  8, 20, 13,  6,  3, 14,  8,  6, 29,  0]),
 array([24, 16, 23, 20,  2, 23,  3, 27, 24, 15, 17, 20,  2, 26,  1]),
 array([10, 20,  6, 13, 13, 20, 11,  1,  6, 16, 29,  7, 23,  1, 23]),
 array([24, 17, 12, 29, 14, 20,  0, 24, 23, 21,  3,  3,  6, 15,  8]),
 array([19,  0,  5, 25, 27,  1, 11,  8,  1,  4, 11, 12, 29,  1, 25]),
 array([22,  8, 17, 26, 21, 14, 13, 17,  8, 23, 17,  1, 15, 15,  3]),
 array([22, 20, 20,  4,  8, 19, 29,  3,  8,  9,  1, 12, 19, 27, 28]),
 array([26, 24, 21, 18,  7,  2, 14, 15, 23, 11,  3, 27, 11, 27, 27]),
 array([24, 14, 25,  6, 22,  4,  3, 24,  1, 13, 15, 14, 27,  9, 23]),
 array([26, 12, 18, 16, 23, 29, 24,  9,  1,  4, 12,  8, 23, 11, 17]),
 array([16, 15,  7,  5, 20,  8, 29, 25, 11, 15,  4, 29, 10,  9,  2]),
 array([28,  2, 25, 27,  8, 14,  8, 28,  9, 14, 25, 11, 26, 22, 22]),
 array([ 3, 25, 21, 10, 27, 18, 28,  9,  5,  4,  0,  6,  0,  5, 13]),
 array([28, 29, 21, 11, 21, 21, 11,  9, 12,  9, 23, 28, 23, 19, 20]),
 array([25, 29,  1, 14,  4, 24, 18,  0, 18,  0,  4, 18, 13, 26,  0]),
 array([21, 21,  1, 24, 25, 28,  8, 22, 14,  2,  9, 17, 22, 12, 22]),
 array([ 3, 13, 10,  5, 15, 19,  6,  1, 22, 13, 13, 23,  2, 14,  9]),
 array([ 6,  1, 27, 14, 14, 21, 29, 13, 21, 20, 20, 22, 13, 24, 25]),
 array([ 9,  0,  3, 13, 20,  7, 14,  9, 15, 14, 13, 26,  6,  9,  7]),
 array([26, 15, 21,  3, 28, 17, 27, 24, 20, 27,  0, 22, 26,  6, 15]),
 array([ 7, 22, 24, 29, 17, 26, 29, 28,  9,  1, 24, 11, 22,  6, 19]),
 array([ 7, 25, 17,  8,  2, 12, 12, 13, 20, 10, 18, 11, 27, 12, 19]),
 array([29, 14,  7, 25, 15, 10, 14,  4,  7, 10,  6, 21, 26, 12, 15]),
 array([20, 12, 10,  4, 18,  3, 12, 20, 29,  0,  0, 28, 20, 11,  3]),
 array([29, 23,  8, 10, 19, 18,  2, 27, 29, 29,  7,  4, 10,  1,  9]),
 array([25, 13, 24,  8, 20, 13, 18,  1, 16, 18,  0, 23, 15, 21, 14]),
 array([13, 11,  8,  0, 26, 13, 15, 20, 19, 13, 21, 24, 20,  3, 24]),
 array([14, 27,  3, 19, 20, 14, 29, 10, 13, 23, 11,  6, 15,  6, 26]),
 array([ 8, 28, 11, 20, 28, 21,  1, 22, 15, 18, 13, 16, 10,  4, 23]),
 array([ 3,  4, 22, 29, 13, 22,  5, 18, 20, 22, 28, 18,  3, 18, 22]),
 array([17,  8, 18, 16,  3, 29, 26,  6,  5,  5,  6, 25, 20, 27, 21]),
 array([13, 21, 24, 14, 17, 12,  6, 19, 28, 20,  6,  7,  6,  7, 19]),
 array([25, 24,  1,  7, 16, 19, 18, 12, 17,  2, 25,  5, 15,  6, 28]),
 array([17, 13, 24,  5, 26,  8, 28, 20,  1, 23, 23,  2,  7,  4,  5]),
 array([ 3, 11,  6,  2,  1, 14, 22, 10, 26, 16, 22,  3, 15, 22,  9]),
 array([18, 22, 16,  9,  3, 13, 14,  7, 29, 19, 29, 23, 25, 18, 14]),
 array([27, 13,  1, 15, 10, 28, 23, 23, 29, 13, 15, 16, 27, 18, 19]),
 array([ 6, 14, 28, 14, 21, 22,  8, 11,  1, 17, 18,  3, 26,  2,  3]),
 array([15, 12, 23, 28, 27,  1, 10,  4, 26, 27, 23, 27, 24,  5, 17]),
 array([29, 11, 18,  1,  3,  3, 29, 19, 21,  2, 20,  3, 29,  9,  1]),
 array([16, 16, 18,  0, 23, 12, 19,  6, 10,  1, 28, 23, 15,  1, 29]),
 array([29, 24, 11,  3,  2, 10, 16,  9,  9, 23, 20, 25,  7, 28, 14]),
 array([ 1, 26,  8, 12, 23, 17, 25, 16,  7,  9,  8, 25,  4,  8, 15]),
 array([10, 13, 19, 25, 13, 18, 12, 29, 11,  8, 14,  7, 16,  4, 21]),
 array([ 9, 20,  0,  4, 18, 20, 22,  7, 17, 20, 19, 27, 14, 27,  1]),
 array([13,  4,  9, 21, 25,  6,  4, 10, 19,  5, 12,  7,  2, 28, 15]),
 array([ 4,  6, 13, 25,  1, 14,  5,  7,  4, 23,  9,  0,  4, 19, 28]),
 array([21, 26, 15, 21, 21, 14, 14, 22,  9, 29, 17, 13, 25, 29, 29]),
 array([15, 25,  8, 28, 14,  2, 29,  4, 14, 14,  3, 27, 24,  4, 23]),
 array([14, 22,  1, 12, 23,  3, 26,  0, 25, 14,  6, 27,  9, 26, 17]),
 array([ 0, 14,  1, 29, 13,  2, 23,  7, 19,  4, 23, 28, 24, 10,  4]),
 array([28, 25,  6,  9, 26, 13, 28,  7,  3, 10, 18, 20, 16,  9, 23]),
 array([23,  2, 27,  3, 14,  6, 24, 16, 25, 13,  7, 21, 10, 15, 23]),
 array([13, 23, 14,  0, 21, 17, 27, 26,  3, 26,  4, 24,  7,  4, 28]),
 array([15, 18, 22,  7, 21, 26, 24, 26, 26, 12, 12,  3, 28, 26,  5]),
 array([19,  5, 24, 12,  4, 16, 21, 17, 15, 20,  6, 21,  5, 25,  3]),
 array([ 8, 11,  4,  8,  8, 25,  4,  3, 13, 10,  2, 23, 13, 17, 22]),
 array([28,  7, 18, 14,  1, 12,  7, 18, 28,  2, 10,  9,  3, 16,  7]),
 array([26, 10,  1, 28, 19,  3,  9, 25, 14, 28, 12, 22, 15,  5, 16]),
 array([ 3, 12,  9, 14, 26,  9, 25, 13,  6,  0,  4, 19, 14,  1,  6]),
 array([10, 13,  4,  5,  1,  9,  9,  4,  8,  0, 12,  9, 24, 23, 24]),
 array([27,  5, 10,  5,  6, 11, 26, 10, 19, 23, 22,  6,  5,  1, 13]),
 array([16, 18,  3, 13, 27, 10, 15,  3, 25,  8, 13, 14, 12, 25,  3]),
 array([16,  8, 15, 20, 11, 18, 21,  0, 28,  8,  1, 23, 25, 21,  7]),
 array([ 9, 27, 26, 16, 22,  5,  4, 16, 19,  2, 12, 15, 10, 10,  5]),
 array([ 5, 22, 26,  6, 20, 24, 13,  1, 20, 28, 21, 11, 22,  1,  2]),
 array([18,  7, 18,  8,  6, 14, 11, 17, 11,  9, 29, 20,  5,  1, 19]),
 array([ 5, 19, 17,  1, 27, 27,  7,  3,  7, 11, 12, 23, 17, 26, 23]),
 array([12,  7, 24,  7, 27,  6, 23, 11,  9, 14, 22, 10, 23,  8, 14]),
 array([ 7, 23, 23,  2,  1,  6, 28, 12, 16, 14,  2, 23, 21, 26,  4]),
 array([13, 23,  6,  0,  4, 15, 14, 25, 16, 15, 16, 20, 28, 19, 28]),
 array([19, 18,  7,  4,  0, 27, 27,  2, 18, 23, 25,  5,  3,  2, 26]),
 array([16,  3, 21, 29, 21,  0, 23, 28, 26, 11,  7, 22,  5, 10, 13]),
 array([ 7, 13, 23, 10, 26, 11, 22, 24,  2, 16, 11,  0, 14, 20, 24]),
 array([24, 29, 24, 25, 25, 14,  5, 23, 11, 21,  8,  0,  0, 23,  9]),
 array([24,  8, 12, 24, 17,  0, 13,  5,  9,  9, 13, 29, 28, 23, 26]),
 array([ 9, 17, 29, 10, 24,  7, 14, 25,  7, 27,  6,  8,  2,  0, 27]),
 array([20,  0, 26, 16,  4, 29,  4, 15, 13, 24,  4, 14, 29,  1, 23]),
 array([ 2, 22,  3, 21,  5, 16, 12, 21, 25, 11, 18,  7,  1,  6, 13]),
 array([29, 16,  1, 23, 16, 11, 25,  6, 19, 16, 15, 10, 24,  6, 28]),
 array([12, 15, 14, 14, 20, 16, 12,  3, 17, 17, 25, 21, 11, 26, 28]),
 array([12, 14, 24, 20,  7, 15,  8,  3, 12, 11, 21, 27, 26,  1,  4]),
 array([22, 29,  1,  0,  5, 26, 12, 16, 19, 28, 10, 16,  1, 25, 21]),
 array([ 5, 25,  0,  3,  2, 13,  3,  8, 27, 22, 19,  9,  4,  5, 12]),
 array([29, 21, 19,  7, 28, 25,  0, 28,  0, 29, 14, 24,  1, 28, 12]),
 array([ 0,  3, 19, 20, 27, 24, 27,  9, 27, 16,  5, 28,  6, 24, 23]),
 array([25,  9, 26, 21,  6,  8, 28,  7, 27,  1, 16, 21, 12,  9, 14]),
 array([ 7,  2, 18, 13, 19,  0, 21, 15,  7,  7, 16,  4,  5, 14, 26]),
 array([25, 11, 12, 26, 24,  6, 15, 23, 23,  2, 16, 16, 22, 16, 24]),
 array([ 2, 21, 20, 16, 16, 15, 15, 24, 17, 25, 11,  8,  2, 15, 29]),
 array([14, 20, 27, 15, 11, 23, 24,  9, 17, 28, 26, 19, 14, 18,  0]),
 array([14,  3,  3, 12, 27, 22,  7,  8,  9, 21, 19, 20, 21,  3,  7]),
 array([ 8, 20,  0, 20, 11, 20, 20, 28, 12, 27,  4, 29, 12,  2, 22]),
 array([12,  4, 13, 17, 23, 18,  2, 15,  2, 16,  3,  0,  0,  7, 24]),
 array([28, 28, 23, 21, 11, 28, 24, 12, 19, 11, 19,  8,  0, 13, 14]),
 array([ 1, 29, 11, 12, 27,  0, 16, 12,  5, 29, 24,  0,  2, 29, 26]),
 array([26, 10,  1,  0,  9, 25, 17,  2, 26,  3, 19,  0, 16,  5, 16]),
 array([ 8, 15, 21, 23,  0, 29, 19,  5, 14, 25, 18, 14, 29,  7, 10]),
 array([ 5, 13, 29, 22, 21, 23, 28,  9, 21, 19,  7, 16, 28, 16, 10]),
 array([17,  2,  5,  4, 17, 16, 16, 17, 10, 10, 22,  4, 24, 15,  8]),
 array([17, 29, 26, 25,  6, 16,  2,  3,  6,  0, 19,  6,  7,  7, 28]),
 array([27,  5,  5, 23,  0,  0,  5,  3, 11,  1, 24, 12,  8, 26, 12]),
 array([ 7, 29, 17, 13, 25, 26,  1, 20,  0,  4, 22, 19, 15, 12, 21]),
 array([12, 27, 17, 26, 26, 18,  9, 25, 16, 15, 26, 12, 10, 10, 22]),
 array([29, 19,  4, 28, 10,  1, 20,  4,  1,  4, 29,  7, 25, 27, 13]),
 array([10,  4, 21, 22, 28, 28, 25,  6, 23, 10, 28, 26, 22,  1, 19]),
 array([ 8, 15, 14, 19, 17, 21, 29, 18,  3, 21, 23, 27, 16, 22,  3]),
 array([21, 20,  3, 28, 27, 25,  3, 21, 23, 29, 20, 24, 13, 10, 15]),
 array([18, 15, 22,  5, 29,  0,  6,  8, 10,  9,  3, 12,  4, 13, 24]),
 array([25,  6, 17, 15, 22, 23, 21, 27, 24, 18, 24, 22,  1, 17, 15]),
 array([15, 23, 23,  1,  6, 15, 22, 11, 25, 14,  7, 17,  8, 26, 13]),
 array([17, 25, 22, 17, 19, 14, 27, 24, 21,  7, 28, 11, 28,  8, 16]),
 array([29,  8, 11, 18,  8, 11, 14, 13, 11, 17, 13, 16,  5, 22, 14]),
 array([28,  5,  3, 17, 21,  2,  8,  0, 13, 17, 14, 13,  6, 12, 16]),
 array([17, 28, 17,  1,  7,  6, 10,  7, 13, 18, 26, 13,  5, 12,  4]),
 array([14,  0, 16,  2, 17,  1, 26, 13, 13,  5,  7, 16, 12, 14,  0]),
 array([ 2, 19,  7,  5,  9, 23,  3, 23,  3, 27, 19, 22, 19, 27, 11]),
 array([ 2, 15, 17,  0, 23,  4, 21, 26,  6, 19, 17,  9, 27, 22, 22]),
 array([ 9, 26,  0, 16,  4,  6,  1,  2, 25, 11, 13, 17, 18, 22,  9]),
 array([28, 17,  1,  4, 17,  8, 16,  4, 21,  4, 20, 26,  4,  0, 26]),
 array([ 2, 11,  3,  1, 13,  9,  5, 18, 22, 23,  6,  2,  6, 10, 29]),
 array([22,  3, 12,  8, 12,  7,  3, 10, 23, 20,  7,  2, 16, 22, 19]),
 array([ 0,  7,  3,  5, 29,  3, 20, 19, 21, 14, 23, 23,  6,  1, 15]),
 array([ 1, 19,  2, 21, 16,  8,  0, 28, 21,  1, 15,  3, 10, 29, 22]),
 array([ 6,  0, 26, 17, 27,  2, 16, 20,  1, 22, 28,  8,  1,  6,  7]),
 array([ 8, 18, 23, 28,  7, 13, 17,  2,  7, 25, 26, 22, 27, 21,  2]),
 array([22,  9,  6, 23,  2,  6, 23, 16, 17, 28,  7, 15,  1,  7,  6]),
 array([28, 20, 14, 13, 17, 26,  2, 10,  3,  9,  7,  8, 10, 18, 16]),
 array([10, 27,  6,  8, 22,  6, 16,  0, 15, 28, 21, 19, 10, 21, 15]),
 array([18, 22, 14,  0,  0, 21, 12, 20,  8, 22,  6, 20, 13,  0, 29]),
 array([ 5,  9,  5, 26,  4, 17,  8,  2, 21, 18, 22, 18,  7, 22,  8]),
 array([29, 14, 21, 24, 23, 20, 23,  1, 19, 23,  4, 12, 13,  3,  7]),
 array([29, 10, 16,  2, 12, 15, 20, 14, 23,  6, 28,  2, 27, 12, 22]),
 array([ 0, 18, 13, 19, 14,  5,  1, 19,  5, 20,  5, 12,  6, 22,  2]),
 array([19, 26, 29, 14, 27, 27, 24, 25,  4, 10, 29,  4, 24, 15, 27]),
 array([10,  3, 14, 21,  0,  4,  7, 29, 23, 23, 11, 15, 11, 15,  1]),
 array([ 7,  2, 11,  6, 14,  1,  5, 25,  5,  3, 11, 28,  3, 10, 27]),
 array([19, 13, 19,  0, 21,  1, 23,  1,  4, 21, 20, 27, 19, 11, 22]),
 array([18, 11, 17,  9,  5,  6,  6, 17, 11, 27, 11,  0, 11, 18, 28]),
 array([22, 12, 23, 23, 22, 25,  0,  8,  8, 16, 20,  2, 13, 17, 28]),
 array([26,  9,  3, 28,  3,  4, 25,  3,  7, 22,  5, 10,  2,  9, 22]),
 array([29, 19, 27, 27, 17,  8, 21, 16, 26, 27,  5,  1, 20, 16,  2]),
 array([26, 12,  9, 13, 26,  5, 26, 29,  2,  2,  7,  0, 11, 28, 27]),

# Random Patches
Combination of row sampling and column/features sampling

In [20]:
bag_e = BaggingClassifier(
estimator=DecisionTreeClassifier(), #Creating Decision Tree as base estimator
n_estimators=500, #Creating 500 Decision Tree models
max_samples=0.25, #Taking 25% random rows for each model
bootstrap=True, #Enabling sampling with replacement for rows
max_features=0.5, #Taking 50% random features for each model
bootstrap_features=True, #Enabling sampling with replacement for features
random_state=42 #Fixing random behavior for same results
)
bag_e.fit(X_train,y_train) 
y_pred = bag_e.predict(X_test) 
print("Random Patches classifier", accuracy_score(y_test,y_pred))

Random Patches classifier 0.9649122807017544

⚠️ IMPORTANT:
 - Dataset is NOT divided equally ❌
 - Each tree randomly samples data ✅ or select data from the dataset 
 - Same row can appear many times ✅ if bootsrap is true 
 - bootstrap=True → repetition allowed

# OBB score
OOB Score (Out-Of-Bag Score) is the accuracy or performance of a bagging model measured using the rows/samples that were not selected during bootstrap training of a particular tree or estimator. you can say that like the X_test

⚠️ OOB works with:
✅ rows/samples
❌ not columns/features

🔥 Used mainly in:
Bagging
Random Forest

In [21]:
bag_e = BaggingClassifier(
estimator=DecisionTreeClassifier(), #Creating Decision Tree as base estimator
n_estimators=500, #Creating 500 Decision Tree models
max_samples=0.25, #Taking 25% random rows for each model
bootstrap=True, #Enabling sampling with replacement
oob_score=True, #Enabling Out Of Bag score calculation
max_features=0.5,   
random_state=42 #Fixing random behavior for same results
)
bag_e.fit(X_train,y_train)
y_pred_e = bag_e.predict(X_test)

In [22]:
print("Random Patches classifier", accuracy_score(y_test,y_pred_e))
print(('OBB score is ',bag_e.oob_score_))

Random Patches classifier 0.9649122807017544
('OBB score is ', 0.9560439560439561)

Bagging Tips

- Bagging generally gives better results than Pasting
- Good results come around the 25% to 50% row sampling mark
- Random patches and subspaces should be used while dealing with high dimensional data
- To find the correct hyperparameter values we can do GridSearchCV/RandomSearchCV

# Apply GridSearch To Find best hyperparamer and best results

In [23]:
from sklearn.model_selection import GridSearchCV

parameters = {
'n_estimators': [50,100,500],
'max_samples': [0.1,0.4,0.7,1.0],
'bootstrap' : [True, False],
'max_features' : [0.1,0.4,0.7,1.0] }

search = GridSearchCV(BaggingClassifier(), parameters, cv=5)

search.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=BaggingClassifier(),
             param_grid={'bootstrap': [True, False],
                         'max_features': [0.1, 0.4, 0.7, 1.0],
                         'max_samples': [0.1, 0.4, 0.7, 1.0],
                         'n_estimators': [50, 100, 500]})

In [25]:
search.best_params_

{'bootstrap': True,
 'max_features': 0.7,
 'max_samples': 0.7,
 'n_estimators': 50}

In [26]:
search.best_score_

np.float64(0.9626373626373625)