<a href="https://colab.research.google.com/github/riteshkrkumarweb/Learning_AI/blob/main/Feature_Construction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import pandas as pd
import numpy as np

import seaborn as sns

from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

In [5]:
df = pd.read_csv('/content/sample_data/tested (2).csv')[['Age','Pclass','SibSp','Parch','Survived']]

In [8]:
df.sample(4)

      Age  Pclass  SibSp  Parch  Survived
86   27.0       3      0      0         1
414  39.0       1      0      0         1
131  53.0       1      0      0         0
348  24.0       2      0      0         0

In [7]:
df.dropna(inplace=True)

In [9]:
X = df.iloc[:,0:4]
y = df.iloc[:,-1]

In [37]:
X.sample(5)

      Age  Pclass  Family_type
254  32.5       3            0
8    18.0       3            0
171  27.0       3            0
412  28.0       3            0
66   18.0       3            0

In [11]:
y.head()

0    0
1    1
2    0
3    0
4    1
Name: Survived, dtype: int64

In [36]:
np.mean(cross_val_score(LogisticRegression(),X,y,scoring='accuracy',cv=25))

np.float64(0.6167032967032967)

# Apply Feature Construction

In [17]:
X['Family_size']= X['SibSp'] + X['Parch'] + 1

In [18]:
X.head()

    Age  Pclass  SibSp  Parch  Family_size
0  34.5       3      0      0            1
1  47.0       3      1      0            2
2  62.0       2      0      0            1
3  27.0       3      0      0            1
4  22.0       3      1      1            3

In [25]:
def myfunc(num):
  if num == 1:
    #alone
    return 0
  elif num >1 and num <=4:
    # small family
    return 1
  else:
    # large family
    return 2

In [26]:
myfunc(4)

1

In [27]:
X['Family_type'] = X['Family_size'].apply(myfunc)

In [29]:
X.sample(5)

      Age  Pclass  SibSp  Parch  Family_size  Family_type
275  20.0       2      1      0            2            1
45   25.0       3      0      0            1            0
323  33.0       1      0      0            1            0
89    2.0       2      1      1            3            1
207  24.0       2      0      0            1            0

In [30]:
X.drop(columns=['SibSp','Parch','Family_size'],inplace=True)

In [31]:
X.head()

    Age  Pclass  Family_type
0  34.5       3            0
1  47.0       3            1
2  62.0       2            0
3  27.0       3            0
4  22.0       3            1

In [34]:
np.mean(cross_val_score(LogisticRegression(),X,y,scoring='accuracy',cv=5))

np.float64(0.617277250113071)