<a href="https://www.kaggle.com/code/riteshkumarweb/gradient-boosting-classification?scriptVersionId=321343652" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/riteshkumarweb/student-dataset/Student_Marks.csv
/kaggle/input/datasets/yasserh/breast-cancer-dataset/breast-cancer.csv

In [ ]:
# ⚡ Gradient Boosting

# Gradient Boosting is an Ensemble Learning algorithm

# 🎯 Goal:
# Improve prediction accuracy
# by reducing errors step-by-step

# 🧠 Idea:
# Models are trained sequentially
# and each new model tries to fix
# errors made by previous models

# 📦 Uses:
# Small Decision Trees as weak learners

# Unlike Bagging:
# ❌ Models are NOT independent

# In Gradient Boosting:
# ✅ Each model learns from previous errors


# 🔁 Working of Gradient Boosting:

# Step 1️⃣
# Train first weak model

# Step 2️⃣
# Calculate errors (Residuals)

# Residual = Actual - Predicted

# Step 3️⃣
# Train next model on residuals/errors

# Step 4️⃣
# Add predictions of new model
# to improve final prediction

# Step 5️⃣
# Repeat sequentially many times


# 📊 Final Prediction:
# Sum of predictions from all weak learners


# ⚡ Gradient Boosting Classifier

# Used for Classification problems

# Example:
# Spam Detection 📧
# Disease Prediction 🏥
# Fraud Detection 💳

# Final prediction:
# Combined prediction from all trees


# 📦 Important Hyperparameters:

# n_estimators
# → Number of weak learners/trees

# learning_rate
# → Contribution of each tree

# Small learning_rate:
# → Slower learning
# → Better generalization

# Large learning_rate:
# → Faster learning
# → Risk of overfitting

# max_depth
# → Maximum depth of each tree

# subsample
# → Fraction of samples used for training each tree

# random_state
# → Ensures reproducible results


# 📊 GradientBoostingClassifier Example

from sklearn.ensemble import GradientBoostingClassifier

model = GradientBoostingClassifier(

    n_estimators=100,
    # 🌳 Number of trees

    learning_rate=0.1,
    # ⚡ Contribution of each tree

    max_depth=3,
    # 🌲 Depth of each tree

    random_state=42
    # 🔁 Reproducible results
)


# ✅ Advantages:
# High accuracy
# Handles complex patterns
# Reduces bias and variance
# Works well on structured/tabular data

# ❌ Disadvantages:
# Slow training (sequential learning)
# Sensitive to overfitting
# Sensitive to hyperparameters
# Harder to tune


# 📊 Simple Diagram:

#          📥 Original Dataset
#                   │
#              🌳 Tree1
#                   │
#            ❌ Residuals
#                   │
#              🌳 Tree2
#                   │
#            ❌ Residuals
#                   │
#              🌳 Tree3
#                   │
#         ➕ Add Predictions
#                   │
#            ✅ Final Prediction

In [3]:
df = pd.read_csv("/kaggle/input/datasets/yasserh/breast-cancer-dataset/breast-cancer.csv")

In [4]:
df

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [5]:
df.drop(columns=['id',],inplace = True)

In [6]:
X = df.iloc[:,1:]
X

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [7]:
y = df.iloc[:,0]
y

0      M
1      M
2      M
3      M
4      M
      ..
564    M
565    M
566    M
567    M
568    B
Name: diagnosis, Length: 569, dtype: object

In [8]:
from sklearn.preprocessing import LabelEncoder
encoding = LabelEncoder()
df['diagnosis'] = encoding.fit_transform(y)

In [9]:
df

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,1,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,1,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,1,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,1,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,1,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,1,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,1,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,1,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,0,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [10]:
df['diagnosis'].value_counts()

diagnosis
0    357
1    212
Name: count, dtype: int64

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Appling Logistic Regression on the Breast Cancer Dataset

In [12]:
lr = LogisticRegression(max_iter=5000)
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)
print('The accuracy for this model is this',accuracy_score(y_test,y_pred) )

scores = cross_val_score(lr, X, y, cv=10, scoring='accuracy')
print(f'The Cross_val_score and mean accuracy of this dataset is: {np.mean(scores):.2f}')

The accuracy for this model is this 0.956140350877193
The Cross_val_score and mean accuracy of this dataset is: 0.95

# Appling Grading Boosting to this Breast Cancer Dataset

In [13]:
from sklearn.ensemble import GradientBoostingClassifier
gd = GradientBoostingClassifier(learning_rate=0.1,n_estimators=1000,)

gd.fit(X_train,y_train)
y_pred_gd = gd.predict(X_test)
print('The accuracy for Grading Boosting model is this',accuracy_score(y_test,y_pred_gd) )

scores_gd = cross_val_score(gd, X, y, cv=10, scoring='accuracy')
print(f'The Cross_val_score and mean accuracy of this dataset on Gradient : {np.mean(scores_gd)}')

The accuracy for Grading Boosting model is this 0.9649122807017544
The Cross_val_score and mean accuracy of this dataset on Gradient : 0.9631578947368421

# Appling GridSearchCV on Gradient Boosting classification to search best_score and best_params for Breast Cancer Dataset

In [18]:
loss= ['log_loss','exponential']
learning_rate = [0.1,0.001,]
n_estimators = [100,200 ]
criterion = ['friedman_mse', 'squared_error']
max_depth = [8,32]
params = {'loss':loss,'learning_rate':learning_rate,'n_estimators':n_estimators,'criterion':criterion,'max_depth':max_depth}
print(params)
from sklearn.model_selection import GridSearchCV
search_gd = GradientBoostingClassifier()
search = GridSearchCV(search_gd, params,scoring='accuracy',n_jobs= -1)
search.fit(X_train,y_train)

{'loss': ['log_loss', 'exponential'], 'learning_rate': [0.1, 0.001], 'n_estimators': [100, 200], 'criterion': ['friedman_mse', 'squared_error'], 'max_depth': [8, 32]}

GridSearchCV(estimator=GradientBoostingClassifier(), n_jobs=-1,
             param_grid={'criterion': ['friedman_mse', 'squared_error'],
                         'learning_rate': [0.1, 0.001],
                         'loss': ['log_loss', 'exponential'],
                         'max_depth': [8, 32], 'n_estimators': [100, 200]},
             scoring='accuracy')

In [19]:
print(search.best_score_)
print(search.best_params_)
test_score = search.score(X_test, y_test)
print(f"Test Set Score: {test_score}")

0.9296703296703297
{'criterion': 'friedman_mse', 'learning_rate': 0.1, 'loss': 'log_loss', 'max_depth': 8, 'n_estimators': 200}
Test Set Score: 0.9385964912280702

In [ ]:
# 2. Score the best model on your separate test set
#test_score = grid_search.score(X_test, y_test)
#print(f"Test Set Score: {test_score}")

# 3. Or manually predict and evaluate
#y_pred = grid_search.predict(X_test)

In [ ]:
#.score(X_test, y_test) - Method 2
#python
#test_score = grid_search.score(X_test, y_test)
#What it does internally:

#python
#def score(self, X_test, y_test):
    #y_pred = self.predict(X_test)           # Step 1: Make predictions
   # accuracy = accuracy_score(y_test, y_pred)  # Step 2: Compare with true labels
    #return accuracy