<a href="https://www.kaggle.com/code/riteshkumarweb/randomforest-regresser-ensemble-learning?scriptVersionId=320209826" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [23]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/shree1992/housedata/output.csv
/kaggle/input/datasets/shree1992/housedata/data.csv
/kaggle/input/datasets/shree1992/housedata/data.dat

In [24]:
# 🌲 RandomForestRegressor

# RandomForestRegressor is an Ensemble Learning algorithm
# used for Regression problems

# 🎯 Goal:
# Predict continuous numerical values

# Example:
# House Price 🏠
# Salary 💰
# Temperature 🌡️

# 🧠 Idea:
# Combine multiple Decision Tree Regressors
# to improve accuracy and reduce overfitting

# 📦 Random Forest uses:
# ✅ Bagging
# ✅ Random Feature Selection


# 🔁 Working:

# Step 1️⃣
# Create multiple random datasets
# using Bootstrap Sampling

# Step 2️⃣
# Train multiple DecisionTreeRegressors

# Step 3️⃣
# Each tree predicts numerical output

# Step 4️⃣
# Take average of all predictions


# 📊 Example:

# Tree1 Prediction → 100
# Tree2 Prediction → 120
# Tree3 Prediction → 110

# Final Prediction:
# (100 + 120 + 110) / 3 = 110


# 📦 Important Hyperparameters:

# n_estimators
# → Number of trees in forest

# max_depth
# → Maximum depth of each tree

# max_features
# → Number of random features used at each split

# min_samples_split
# → Minimum samples required to split node

# min_samples_leaf
# → Minimum samples required in leaf node


# ✅ Advantages:
# Better accuracy
# Reduces overfitting
# Handles non-linear data
# Stable predictions

# ❌ Disadvantages:
# Slower
# More memory usage
# Harder to interpret


# 📊 Simple Diagram:

#                📥 Original Dataset
#                         │
#       ┌─────────────────┼─────────────────┐
#       │                 │                 │
#   🌳 Tree1          🌳 Tree2          🌳 Tree3
#       │                 │                 │
#      100               120               110
#       └─────────────────┼─────────────────┘
#                         │
#                 📊 Average Prediction
#                         │
#                    ✅ 110

In [25]:
df = pd.read_csv('/kaggle/input/datasets/shree1992/housedata/data.csv')
df

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,3.130000e+05,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2.384000e+06,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,3.420000e+05,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,4.200000e+05,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,5.500000e+05,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,2014-07-09 00:00:00,3.081667e+05,3.0,1.75,1510,6360,1.0,0,0,4,1510,0,1954,1979,501 N 143rd St,Seattle,WA 98133,USA
4596,2014-07-09 00:00:00,5.343333e+05,3.0,2.50,1460,7573,2.0,0,0,3,1460,0,1983,2009,14855 SE 10th Pl,Bellevue,WA 98007,USA
4597,2014-07-09 00:00:00,4.169042e+05,3.0,2.50,3010,7014,2.0,0,0,3,3010,0,2009,0,759 Ilwaco Pl NE,Renton,WA 98059,USA
4598,2014-07-10 00:00:00,2.034000e+05,4.0,2.00,2090,6630,1.0,0,0,3,1070,1020,1974,0,5148 S Creston St,Seattle,WA 98178,USA
4599,2014-07-10 00:00:00,2.206000e+05,3.0,2.50,1490,8102,2.0,0,0,4,1490,0,1990,0,18717 SE 258th St,Covington,WA 98042,USA

In [26]:
df.isnull().sum()

date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
street           0
city             0
statezip         0
country          0
dtype: int64

In [27]:
df.drop(columns=['date','waterfront','view','city','statezip','country','street'],inplace=True)

In [28]:
df

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,condition,sqft_above,sqft_basement,yr_built,yr_renovated
0,3.130000e+05,3.0,1.50,1340,7912,1.5,3,1340,0,1955,2005
1,2.384000e+06,5.0,2.50,3650,9050,2.0,5,3370,280,1921,0
2,3.420000e+05,3.0,2.00,1930,11947,1.0,4,1930,0,1966,0
3,4.200000e+05,3.0,2.25,2000,8030,1.0,4,1000,1000,1963,0
4,5.500000e+05,4.0,2.50,1940,10500,1.0,4,1140,800,1976,1992
...,...,...,...,...,...,...,...,...,...,...,...
4595,3.081667e+05,3.0,1.75,1510,6360,1.0,4,1510,0,1954,1979
4596,5.343333e+05,3.0,2.50,1460,7573,2.0,3,1460,0,1983,2009
4597,4.169042e+05,3.0,2.50,3010,7014,2.0,3,3010,0,2009,0
4598,2.034000e+05,4.0,2.00,2090,6630,1.0,3,1070,1020,1974,0
4599,2.206000e+05,3.0,2.50,1490,8102,2.0,4,1490,0,1990,0

In [29]:
X = df.iloc[:,1:]
X

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,condition,sqft_above,sqft_basement,yr_built,yr_renovated
0,3.0,1.50,1340,7912,1.5,3,1340,0,1955,2005
1,5.0,2.50,3650,9050,2.0,5,3370,280,1921,0
2,3.0,2.00,1930,11947,1.0,4,1930,0,1966,0
3,3.0,2.25,2000,8030,1.0,4,1000,1000,1963,0
4,4.0,2.50,1940,10500,1.0,4,1140,800,1976,1992
...,...,...,...,...,...,...,...,...,...,...
4595,3.0,1.75,1510,6360,1.0,4,1510,0,1954,1979
4596,3.0,2.50,1460,7573,2.0,3,1460,0,1983,2009
4597,3.0,2.50,3010,7014,2.0,3,3010,0,2009,0
4598,4.0,2.00,2090,6630,1.0,3,1070,1020,1974,0
4599,3.0,2.50,1490,8102,2.0,4,1490,0,1990,0

In [30]:
y = df.iloc[:,0]
y

0       3.130000e+05
1       2.384000e+06
2       3.420000e+05
3       4.200000e+05
4       5.500000e+05
            ...
4595    3.081667e+05
4596    5.343333e+05
4597    4.169042e+05
4598    2.034000e+05
4599    2.206000e+05
Name: price, Length: 4600, dtype: float64

In [31]:
df['price'].value_counts()

price
0.000000         49
300000.000000    42
400000.000000    31
600000.000000    29
450000.000000    29
                 ..
691000.000000     1
282766.666667     1
406062.500000     1
473200.000000     1
454790.000000     1
Name: count, Length: 1741, dtype: int64

# Applying Linear Regression with cross_val_score

In [32]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score
model1 = LinearRegression()
model1.fit(X_train,y_train)
y_pred1 = model1.predict(X_test)
score =  r2_score(y_test,y_pred1)
print('This is the r2_score',score*100)

from sklearn. model_selection import cross_val_score
print(np.mean(cross_val_score(model1,X,y,cv=10,scoring='r2')))

This is the r2_score 3.019705197732503
0.5095003585654577

# Applying Bagging Regressor with the Decesion Tree

In [33]:
from sklearn.ensemble import BaggingRegressor
from sklearn.tree import DecisionTreeRegressor 
bag = BaggingRegressor(estimator=DecisionTreeRegressor())
bag.fit(X_train,y_train)
y_pred2 = bag.predict(X_test)
score =  r2_score(y_test,y_pred2)
print(f'This is the r2_score score {score}')
from sklearn. model_selection import cross_val_score
print('This is the means of 10 split evaluation',np.mean(cross_val_score(bag ,X,y,cv=10,scoring='r2')))

This is the r2_score score 0.018033792808313742
This is the means of 10 split evaluation 0.04724380284708257

# Applying Random Forest Regressor

In [34]:
from sklearn.ensemble import RandomForestRegressor

# Create the model
model_d = RandomForestRegressor(max_features = 'sqrt', random_state=42)

model_d.fit(X_train,y_train)
y_pred3 = model_d.predict(X_test)
score =  r2_score(y_test,y_pred3)
print(score)
from sklearn. model_selection import cross_val_score
print('This is the means of 10 split evaluation',np.mean(cross_val_score(model_d ,X,y,cv=10,scoring='r2')))
#Here is hightest Accuracy

0.028979556219151492
This is the means of 10 split evaluation 0.428257178690383

# 3 ways to Check the Data with manually

In [40]:
check_data = [[3.0,	1.50,	1340,	7912,	1.5, 3,	1340,	0,	1955,	2005]]
model_d.predict(check_data)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

array([335874.33333333])

In [47]:
y = np.array([3.0,	1.50,	1340,	7912,	1.5, 3,	1340,	0,	1955,	2005]).reshape(1,10)
model_d.predict(y)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

array([335874.33333333])

In [55]:
data = pd.DataFrame(
    [[3.0,1.50,1340,7912,1.5,3,1340,0,1955,2005]],
    columns=X.columns
)

results = model_d.predict(data)
print(data)
print('The prediction of this data is ',results)

   bedrooms  bathrooms  sqft_living  sqft_lot  floors  condition  sqft_above  \
0       3.0        1.5         1340      7912     1.5          3        1340

   sqft_basement  yr_built  yr_renovated
0              0      1955          2005
The prediction of this data is  [335874.33333333]

In [36]:
n_estimators = [20,60,100,120]
max_features = [0.2,0.6,1.0, None]
max_depth = [2,8,None]
max_samples = [0.5,0.75,1.0]
bootstrap= [True,False] 
criterion = ['squared_error', 'absolute_error', 'friedman_mse', 'poisson']

params = {
'n_estimators' : n_estimators,
'max_features' : max_features,
'max_depth' : max_depth,
'max_samples' : max_samples,
'bootstrap': bootstrap,
'criterion' : criterion,
}
print(params)

{'n_estimators': [20, 60, 100, 120], 'max_features': [0.2, 0.6, 1.0, None], 'max_depth': [2, 8, None], 'max_samples': [0.5, 0.75, 1.0], 'bootstrap': [True, False], 'criterion': ['squared_error', 'absolute_error', 'friedman_mse', 'poisson']}

In [37]:
from sklearn.model_selection import GridSearchCV
rm = RandomForestRegressor()
search = GridSearchCV(estimator=rm,param_grid=params,scoring='r2',cv=3 ,n_jobs = -1)
#search.fit(X_train,y_train)