<a href="https://colab.research.google.com/github/riteshkrkumarweb/Learning_AI/blob/main/Use_ColumnTransformer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_csv('/content/me1.csv')

In [ ]:
df.iloc[2, 1] = np.nan
df.iloc[5, 1] = np.nan

In [ ]:
df.sample(10)

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Family_Income,Teacher_Quality,School_Type,Parental_Education_Level,Gender,Exam_Score
1924,32,88.0,7,83,Low,High,Private,Postgraduate,Male,73
189,11,62.0,5,82,High,Medium,Private,College,Male,64
5651,20,66.0,6,91,Medium,High,Public,High School,Male,65
6521,20,82.0,6,94,Low,Medium,Private,High School,Male,68
5872,22,79.0,7,59,Medium,Medium,Public,College,Male,66
14,10,78.0,8,74,Low,Medium,Private,Postgraduate,Male,65
1998,19,95.0,9,85,Low,Medium,Public,College,Male,69
284,33,62.0,10,78,Medium,Medium,Private,High School,Female,68
240,15,87.0,4,54,Medium,Medium,Public,NaN,Male,65
2005,21,90.0,8,60,Low,Medium,Public,College,Female,66

In [ ]:
df.isnull().sum()

Hours_Studied      0
Attendance         2
Sleep_Hours        0
Previous_Scores    0
Family_Income      0
School_Type        0
Gender             0
Exam_Score         0
dtype: int64

In [ ]:
df.drop(columns=['Parental_Education_Level','Teacher_Quality'],inplace=True)

In [ ]:
df.sample(5)

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Family_Income,Teacher_Quality,School_Type,Parental_Education_Level,Gender,Exam_Score
1971,2,96.0,9,77,Medium,NaN,Public,High School,Female,65
3136,26,64.0,5,64,High,Medium,Public,High School,Male,64
959,23,94.0,8,62,Low,Medium,Public,Postgraduate,Female,69
1979,22,84.0,9,88,Low,High,Private,Postgraduate,Male,71
2005,21,90.0,8,60,Low,Medium,Public,College,Female,66

In [ ]:
df.shape

(6607, 8)

In [ ]:
X = df[['Hours_Studied',	'Attendance',	'Sleep_Hours',	'Previous_Scores',	'Family_Income',	'School_Type',	'Gender']]
y = df['Exam_Score']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [ ]:
X_train.shape

(5285, 7)

In [ ]:
X_test.shape

(1322, 7)

In [ ]:
from sklearn.compose import ColumnTransformer
# import the required libraries

import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
from scipy import sparse
transformer = ColumnTransformer(transformers=[
    ('tnf0',SimpleImputer(),['Attendance']),
    ('tnf3',OrdinalEncoder(categories=[['Low','Medium','High']]),['Family_Income']),
    ('tnf6',OneHotEncoder(sparse_output=False,drop='first'),['Gender','School_Type']),
],remainder='passthrough')

In [ ]:
transformer.fit_transform(X_train).shape

(5285, 7)

In [ ]:
transformer.transform(X_test).shape

(1322, 7)